name: Start release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to use"
        required: true
        type: string
      dry_run:
        description: "Run release sanity checks without creating the release"
        default: true
        type: boolean


jobs:
  validation:
    name: Release sanity
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    uses: ./.github/workflows/release_sanity.yml

  release:
    name: Release mechanism
    if: ${{ !inputs.dry_run }}
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    permissions:
      contents: write
    uses: ./.github/workflows/release_release.yml
